/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author santi_000
 */
public class CaidaTension extends javax.swing.JFrame {
    
    String resultado = null;

    /**
     * @return the fieldDpms
     */
    public javax.swing.JTextField getFieldDpms() {
        return fieldDpms;
    }

    /**
     * @return the fieldLongitud
     */
    public javax.swing.JTextField getFieldLongitud() {
        return fieldLongitud;
    }

    /**
     * @return the fieldTension
     */
    public javax.swing.JTextField getFieldTension() {
        return fieldTension;
    }

    /**
     * Creates new form Inicio
     */
    public CaidaTension() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        botonExit = new javax.swing.JButton();
        botonBack = new javax.swing.JButton();
        botonSimbolos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelDpms = new javax.swing.JLabel();
        labelLongitud = new javax.swing.JLabel();
        labelTensión = new javax.swing.JLabel();
        fieldTension = new javax.swing.JTextField();
        fieldDpms = new javax.swing.JTextField();
        fieldLongitud = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelTensión1 = new javax.swing.JLabel();
        fieldSeccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botonCalcular = new javax.swing.JButton();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Caída de Tensión");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 260, 30));

        botonExit.setText("Salir");
        botonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExitActionPerformed(evt);
            }
        });
        getContentPane().add(botonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        botonBack.setText("Atrás");
        botonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBackActionPerformed(evt);
            }
        });
        getContentPane().add(botonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        botonSimbolos.setText("Símbolos");
        botonSimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSimbolosActionPerformed(evt);
            }
        });
        getContentPane().add(botonSimbolos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDpms.setText("DPMS  = ");
        jPanel1.add(labelDpms, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        labelLongitud.setText("Longitud =");
        jPanel1.add(labelLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 20));

        labelTensión.setText("Sección = ");
        jPanel1.add(labelTensión, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        fieldTension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTensionActionPerformed(evt);
            }
        });
        jPanel1.add(fieldTension, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 80, -1));

        fieldDpms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDpmsActionPerformed(evt);
            }
        });
        jPanel1.add(fieldDpms, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, -1));

        fieldLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLongitudActionPerformed(evt);
            }
        });
        jPanel1.add(fieldLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 80, -1));

        jLabel1.setText("W");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 20, 20));

        jLabel2.setText("m");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel3.setText("mm2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 30, -1));

        labelTensión1.setText("Tensión = ");
        jPanel1.add(labelTensión1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        fieldSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSeccionActionPerformed(evt);
            }
        });
        jPanel1.add(fieldSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, -1));

        jLabel4.setText("V");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 10, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 420, 30));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 270, 20));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, 20));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 226, 290, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 470, 290));

        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        jFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 487, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonExitActionPerformed

    private void botonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBackActionPerformed
        Inicio inicioVentana = new Inicio();
        inicioVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonBackActionPerformed

    private void botonSimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSimbolosActionPerformed
        CaidaTensiónSimbolos caidaTensionSimbolosVentana = new CaidaTensiónSimbolos();
        caidaTensionSimbolosVentana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSimbolosActionPerformed

    private void fieldTensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTensionActionPerformed

    private void fieldDpmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDpmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDpmsActionPerformed

    private void fieldLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLongitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLongitudActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        int potenciaValor = Integer.parseInt(fieldDpms.getText());
        int longitudValor = Integer.parseInt(fieldLongitud.getText());
        int tensionValor = Integer.parseInt(fieldTension.getText());
        double seccionValor = Double.parseDouble(fieldSeccion.getText());
        double rho = 1 / 56d;
        int intensidadValor = potenciaValor / tensionValor;
        double resistivValor = 2 * rho * longitudValor / seccionValor;
        
        double caidaTension = intensidadValor * resistivValor;
        
        if (caidaTension < 4) {
            resultado = "La sección de cable es correcta.";
      }
        else if (caidaTension >= 4 && caidaTension < 6.6) {
            resultado = "La sección es aceptable, pero es recomendable"
                    + " una sección mayor.";
      }
        else if (caidaTension >= 6.6) {
            resultado = "La sección de cable es muy pequeña. "
                    + "Haz el calculo con una sección mayor";
      }
       
        String intensidad = "La intensidad es: " + intensidadValor + " A";
        String resistividad = "La resistividad es: " + resistivValor + " Ω";
        String rhoValor = "El valor de rho para el cobre es: " + rho + " Ω*m";
        String caidaTensionresult = "La caida de tensión es: " + caidaTension + " V";
        
        
        jLabel8.setText(intensidad);
        jLabel9.setText(resistividad);
        jLabel10.setText(caidaTensionresult);
        jLabel5.setText(resultado);
        
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void fieldSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaidaTension.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaidaTension.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaidaTension.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaidaTension.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaidaTension().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBack;
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonExit;
    private javax.swing.JButton botonSimbolos;
    public javax.swing.JTextField fieldDpms;
    private javax.swing.JTextField fieldLongitud;
    private javax.swing.JTextField fieldSeccion;
    private javax.swing.JTextField fieldTension;
    private javax.swing.JLabel jFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDpms;
    private javax.swing.JLabel labelLongitud;
    private javax.swing.JLabel labelTensión;
    private javax.swing.JLabel labelTensión1;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
